import re,time,sys
que=str(sys.argv[1])
def delayed_print(message):
    for i in message:
        print(i,end='')
        time.sleep(0.01)
    print()
def message_probability(user_message,recognised_words,single_response=False,required_words=[]):
    message_certainity=0
    has_required_words=True
    for word in user_message:
        if word in recognised_words:
            message_certainity+=1
    percentage=float(message_certainity)/float(len(recognised_words))
    for word in required_words:
        if word not in user_message:
            has_required_words=False
            break
    if has_required_words or single_response:
        return int(percentage*100)
    else:
        return 0
def check_all_messages(message):
    highest_prob_list={}
    def response(bot_response,list_of_words,single_response=False,required_words=[]):
        nonlocal highest_prob_list
        highest_prob_list[bot_response]=message_probability(message,list_of_words,single_response,required_words)
    response('Nice talking to you , Bye!',['bye',"farewell","goodbye","adios","see you later","cheerio","au revoir","ciao","ta-ta","so long","until we meet again"],single_response=True)
    response('hello',['hello','hi','heya','hola','sup'],single_response=True)
    response('I am doing fine wht about you?',['how','are','you','doing'],required_words=['how'])
    response('Thank you',['i','like','love','bert'],required_words=['like','love','bert'])
    response("Cricket is the national sport of India.", ["national", "sport", "india", "cricket"])
    response("Sachin Tendulkar is known as the 'God of Cricket'.", ["sachin", "tendulkar", "god", "cricket"])
    response("England won the ICC Cricket World Cup in 2019.", ["england", "icc", "world", "cup", "2019"])
    response("The three formats of cricket are Test, One Day International (ODI), and Twenty20 (T20).",
             ["three", "formats", "test", "one", "day", "international", "odi", "twenty20", "t20"])
    response("Brian Lara holds the record for the highest individual score in Test cricket.", ["brian", "lara", "record", "highest", "score", "test", "cricket"])
    response("India won the first-ever ICC T20 World Cup.", ["india", "first", "icc", "t20", "world", "cup"])
    response("Virat Kohli is the current captain of the Indian cricket team in Test matches.",
             ["virat", "kohli", "current", "captain", "indian", "team", "test", "matches"])
    response("LBW stands for Leg Before Wicket in cricket.", ["lbw", "leg", "before", "wicket", "cricket"])
    response("There are 11 players in a cricket team.", ["11", "players", "cricket", "team"])
    response("A Test cricket match typically lasts for five days.", ["test", "cricket", "match", "five", "days"])
    response("Rohit Sharma holds the record for the most runs scored in a single edition of the ICC Cricket World Cup.",
             ["rohit", "sharma", "record", "most", "runs", "single", "edition", "icc", "cricket", "world", "cup"])
    response("The nickname of the Australian cricket team is the 'Baggy Greens'.", ["nickname", "australian", "team", "baggy", "greens"])
    response("Muttiah Muralitharan has taken the most wickets in international cricket.", ["muttiah", "muralitharan", "most", "wickets", "international", "cricket"])
    response("Wasim Akram is known as the 'Sultan of Swing' in cricket.", ["wasim", "akram", "sultan", "swing", "cricket"])
    response("The trophy awarded to the winner of the Ashes series between England and Australia is called 'The Ashes'.",
             ["trophy", "winner", "ashes", "series", "england", "australia"])
    response("The Indian Premier League (IPL) is a professional Twenty20 cricket league in India.", ["indian", "premier", "league", "ipl"])
    response("The Mumbai Indians is the most successful team in IPL history with the most titles.", ["mumbai", "indians", "most", "successful", "team", "ipl"])
    response("The Chennai Super Kings has won the IPL title the second most number of times.", ["chennai", "super", "kings", "second", "most", "times", "ipl"])
    response("The Orange Cap is awarded to the leading run-scorer in each IPL season.", ["orange", "cap", "leading", "run-scorer", "ipl", "season"])
    response("The Purple Cap is awarded to the leading wicket-taker in each IPL season.", ["purple", "cap", "leading", "wicket-taker", "ipl", "season"])
    response("The IPL was founded by the Board of Control for Cricket in India (BCCI) in 2008.", ["founded", "board", "control", "cricket", "india", "bcci", "2008"])
    response("The Mumbai Indians won the IPL in 2020.", ["mumbai", "indians", "won", "ipl", "2020"])
    response("The Kolkata Knight Riders won the IPL in 2012 and 2014.", ["kolkata", "knight", "riders", "won", "ipl", "2012", "2014"])
    response("The Rajasthan Royals won the inaugural IPL season in 2008.", ["rajasthan", "royals", "won", "inaugural", "ipl", "2008"])
    # IPL-related responses (continued)
    response("The Orange Cap is awarded to the leading run-scorer in each IPL season.",
             ["orange", "cap", "leading", "run-scorer", "ipl", "season"])
    response("The Purple Cap is awarded to the leading wicket-taker in each IPL season.",
             ["purple", "cap", "leading", "wicket-taker", "ipl", "season"])
    response("The IPL playoffs consist of Qualifier 1, Eliminator, Qualifier 2, and the Final.",
             ["ipl", "playoffs", "qualifier", "eliminator", "final"])
    response("The IPL auction is held annually to buy players for each team.",
             ["ipl", "auction", "annually", "buy", "players", "team"])
    response("The Sunrisers Hyderabad won the IPL in 2016.", ["sunrisers", "hyderabad", "won", "ipl", "2016"])
    response("The Delhi Capitals reached the IPL final for the first time in 2020.", ["delhi", "capitals", "reached", "final", "ipl", "2020"])
    response("The Rajasthan Royals won the IPL under the captaincy of Shane Warne in 2008.", ["rajasthan", "royals", "won", "captaincy", "shane", "warne", "ipl", "2008"])
    response("The Mumbai Indians have won the IPL five times, the most by any team.", ["mumbai", "indians", "won", "ipl", "five", "times"])
    response("Chennai Super Kings made a comeback in IPL 2018 after a two-year suspension.", ["chennai", "super", "kings", "comeback", "ipl", "2018", "suspension"])
    response("Chris Gayle holds the record for the highest individual score in an IPL match.", ["chris", "gayle", "record", "highest", "individual", "score", "ipl", "match"])
    response("The IPL 2021 season was held in the United Arab Emirates (UAE) due to the COVID-19 pandemic.", ["ipl", "2021", "season", "united", "arab", "emirates", "uae", "covid-19", "pandemic"])
    response("The Royal Challengers Bangalore has not won an IPL title yet.", ["royal", "challengers", "bangalore", "not", "won", "ipl", "title", "yet"])
    response("Kolkata Knight Riders won consecutive IPL titles in 2012 and 2014.", ["kolkata", "knight", "riders", "consecutive", "ipl", "titles", "2012", "2014"])
    response("Virat Kohli holds the record for the most runs in IPL history.", ["virat", "kohli", "record", "most", "runs", "ipl", "history"])
    response("The IPL 2020 season was played in the United Arab Emirates (UAE) due to the COVID-19 pandemic.",
             ["ipl", "2020", "season", "played", "united", "arab", "emirates", "uae", "covid-19", "pandemic"])
    response("Mumbai Indians won the IPL title in 2019.", ["mumbai", "indians", "won", "ipl", "2019"])
    response("The Delhi Capitals reached their first IPL final in 2020.", ["delhi", "capitals", "reached", "first", "ipl", "final", "2020"])
    response("Kolkata Knight Riders won the IPL in 2012 and 2014 under the captaincy of Gautam Gambhir.", ["kolkata", "knight", "riders", "won", "ipl", "2012", "2014", "captaincy", "gautam", "gambhir"])
    response("Rajasthan Royals won the inaugural IPL season in 2008 under the captaincy of Shane Warne.", ["rajasthan", "royals", "won", "inaugural", "ipl", "2008", "captaincy", "shane", "warne"])
    response("Sunrisers Hyderabad won the IPL in 2016 under the captaincy of David Warner.", ["sunrisers", "hyderabad", "won", "ipl", "2016", "captaincy", "david", "warner"])
    response("The IPL 2021 season saw the emergence of young talent like Harshal Patel and Avesh Khan.", ["ipl", "2021", "season", "emergence", "young", "talent", "harshal", "patel", "avesh", "khan"])
    
    response("MS Dhoni led the Chennai Super Kings to victory in the IPL in 2010 and 2011.", ["ms", "dhoni", "led", "chennai", "super", "kings", "victory", "ipl", "2010", "2011"])
    response("Under MS Dhoni's captaincy, the Chennai Super Kings emerged victorious in the IPL in 2010 and 2011.", ["ms", "dhoni", "captaincy", "chennai", "super", "kings", "emerged", "victorious", "ipl", "2010", "2011"])
    response("MS Dhoni's leadership played a crucial role in the Chennai Super Kings' triumphs in the IPL in 2010 and 2011.", ["ms", "dhoni", "leadership", "crucial", "role", "chennai", "super", "kings", "triumphs", "ipl", "2010", "2011"])
    response("The Chennai Super Kings clinched the IPL trophy under the captaincy of MS Dhoni in 2010 and 2011.", ["chennai", "super", "kings", "clinched", "ipl", "trophy", "captaincy", "ms", "dhoni", "2010", "2011"])
    response("MS Dhoni's tactical genius guided the Chennai Super Kings to IPL glory in 2010 and 2011.", ["ms", "dhoni", "tactical", "genius", "guided", "chennai", "super", "kings", "ipl", "glory", "2010", "2011"])
    response("Under MS Dhoni's guidance, the Chennai Super Kings emerged victorious in the IPL in 2010 and 2011.", ["ms", "dhoni", "guidance", "chennai", "super", "kings", "emerged", "victorious", "ipl", "2010", "2011"])
    response("MS Dhoni's astute captaincy propelled the Chennai Super Kings to IPL success in 2010 and 2011.", ["ms", "dhoni", "astute", "captaincy", "propelled", "chennai", "super", "kings", "ipl", "success", "2010", "2011"])
    response("The Chennai Super Kings' triumphs in the IPL in 2010 and 2011 were a testament to MS Dhoni's leadership skills.", ["chennai", "super", "kings", "triumphs", "ipl", "2010", "2011", "testament", "ms", "dhoni", "leadership", "skills"])
    response("MS Dhoni's strategic acumen was instrumental in the Chennai Super Kings' victory in the IPL in 2010 and 2011.", ["ms", "dhoni", "strategic", "acumen", "instrumental", "chennai", "super", "kings", "victory", "ipl", "2010", "2011"])
    response("The Chennai Super Kings' victories in the IPL in 2010 and 2011 can be credited to MS Dhoni's exceptional captaincy.", ["chennai", "super", "kings", "victories", "ipl", "2010", "2011", "credited", "ms", "dhoni", "exceptional", "captaincy"])
    response("MS Dhoni's composed demeanor under pressure was evident during the Chennai Super Kings' IPL wins in 2010 and 2011.", ["ms", "dhoni", "composed", "demeanor", "pressure", "evident", "chennai", "super", "kings", "ipl", "wins", "2010", "2011"])
    response("Under MS Dhoni's leadership, the Chennai Super Kings displayed remarkable consistency in the IPL, especially in 2010 and 2011.", ["ms", "dhoni", "leadership", "chennai", "super", "kings", "remarkable", "consistency", "ipl", "2010", "2011"])
    response("MS Dhoni's calm and collected approach was a defining factor in the Chennai Super Kings' success in the IPL in 2010 and 2011.", ["ms", "dhoni", "calm", "collected", "approach", "defining", "factor", "chennai", "super", "kings", "success", "ipl", "2010", "2011"])
    response("The Chennai Super Kings' dominance in the IPL was exemplified by their back-to-back titles in 2010 and 2011 under MS Dhoni's captaincy.", ["chennai", "super", "kings", "dominance", "ipl", "exemplified", "back-to-back", "titles", "2010", "2011", "ms", "dhoni", "captaincy"])
    response("MS Dhoni's strategic brilliance was on full display as the Chennai Super Kings clinched consecutive IPL titles in 2010 and 2011.", ["ms", "dhoni", "strategic", "brilliance", "display", "chennai", "super", "kings", "clinched", "consecutive", "ipl", "titles", "2010", "2011"])
    response("Under MS Dhoni's astute captaincy, the Chennai Super Kings emerged as a dominant force in the IPL, particularly in 2010 and 2011.", ["ms", "dhoni", "astute", "captaincy", "chennai", "super", "kings", "emerged", "dominant", "force", "ipl", "2010", "2011"])
    response("MS Dhoni's ability to remain calm under pressure was instrumental in the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "ability", "remain", "calm", "pressure", "instrumental", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' victories in the IPL in 2010 and 2011 showcased MS Dhoni's exceptional leadership qualities.", ["chennai", "super", "kings", "victories", "ipl", "2010", "2011", "showcased", "ms", "dhoni", "exceptional", "leadership", "qualities"])
    response("MS Dhoni's innovative captaincy tactics were key to the Chennai Super Kings' success in the IPL in 2010 and 2011.", ["ms", "dhoni", "innovative", "captaincy", "tactics", "key", "chennai", "super", "kings", "success", "ipl", "2010", "2011"])
    response("Under MS Dhoni's leadership, the Chennai Super Kings became the team to beat in the IPL, particularly in 2010 and 2011.", ["ms", "dhoni", "leadership", "chennai", "super", "kings", "team", "beat", "ipl", "2010", "2011"])

    response("MS Dhoni led the Chennai Super Kings to victory in the IPL in 2010 and 2011.", ["ms", "dhoni", "led", "chennai", "super", "kings", "victory", "ipl", "2010", "2011"])
    response("Under MS Dhoni's captaincy, the Chennai Super Kings emerged victorious in the IPL in 2010 and 2011.", ["ms", "dhoni", "captaincy", "chennai", "super", "kings", "emerged", "victorious", "ipl", "2010", "2011"])
    response("MS Dhoni's leadership played a crucial role in the Chennai Super Kings' triumphs in the IPL in 2010 and 2011.", ["ms", "dhoni", "leadership", "crucial", "role", "chennai", "super", "kings", "triumphs", "ipl", "2010", "2011"])
    response("The Chennai Super Kings clinched the IPL trophy under the captaincy of MS Dhoni in 2010 and 2011.", ["chennai", "super", "kings", "clinched", "ipl", "trophy", "captaincy", "ms", "dhoni", "2010", "2011"])
    response("MS Dhoni's tactical genius guided the Chennai Super Kings to IPL glory in 2010 and 2011.", ["ms", "dhoni", "tactical", "genius", "guided", "chennai", "super", "kings", "ipl", "glory", "2010", "2011"])
    response("Under MS Dhoni's guidance, the Chennai Super Kings emerged victorious in the IPL in 2010 and 2011.", ["ms", "dhoni", "guidance", "chennai", "super", "kings", "emerged", "victorious", "ipl", "2010", "2011"])
    response("MS Dhoni's astute captaincy propelled the Chennai Super Kings to IPL success in 2010 and 2011.", ["ms", "dhoni", "astute", "captaincy", "propelled", "chennai", "super", "kings", "ipl", "success", "2010", "2011"])
    response("The Chennai Super Kings' triumphs in the IPL in 2010 and 2011 were a testament to MS Dhoni's leadership skills.", ["chennai", "super", "kings", "triumphs", "ipl", "2010", "2011", "testament", "ms", "dhoni", "leadership", "skills"])
    response("MS Dhoni's strategic acumen was instrumental in the Chennai Super Kings' victory in the IPL in 2010 and 2011.", ["ms", "dhoni", "strategic", "acumen", "instrumental", "chennai", "super", "kings", "victory", "ipl", "2010", "2011"])
    response("The Chennai Super Kings' victories in the IPL in 2010 and 2011 can be credited to MS Dhoni's exceptional captaincy.", ["chennai", "super", "kings", "victories", "ipl", "2010", "2011", "credited", "ms", "dhoni", "exceptional", "captaincy"])
    response("MS Dhoni's calm demeanor under pressure was evident during the Chennai Super Kings' IPL wins in 2010 and 2011.", ["ms", "dhoni", "calm", "demeanor", "pressure", "evident", "chennai", "super", "kings", "ipl", "wins", "2010", "2011"])
    response("The Chennai Super Kings' dominance in the IPL in 2010 and 2011 was fueled by MS Dhoni's leadership.", ["chennai", "super", "kings", "dominance", "ipl", "2010", "2011", "fueled", "ms", "dhoni", "leadership"])
    response("MS Dhoni's ability to make crucial decisions was pivotal in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "ability", "crucial", "decisions", "pivotal", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' consistency in the IPL in 2010 and 2011 was attributed to MS Dhoni's captaincy.", ["chennai", "super", "kings", "consistency", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "captaincy"])
    response("MS Dhoni's cool-headed approach was a key factor in the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "cool-headed", "approach", "key", "factor", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' remarkable performance in the IPL in 2010 and 2011 was orchestrated by MS Dhoni.", ["chennai", "super", "kings", "remarkable", "performance", "ipl", "2010", "2011", "orchestrated", "ms", "dhoni"])
    response("MS Dhoni's composure in tense situations was crucial for the Chennai Super Kings' success in the IPL in 2010 and 2011.", ["ms", "dhoni", "composure", "tense", "situations", "crucial", "chennai", "super", "kings", "success", "ipl", "2010", "2011"])
    response("The Chennai Super Kings' resilience in the IPL in 2010 and 2011 was a testament to MS Dhoni's leadership qualities.", ["chennai", "super", "kings", "resilience", "ipl", "2010", "2011", "testament", "ms", "dhoni", "leadership", "qualities"])
    response("MS Dhoni's captaincy during the IPL in 2010 and 2011 set a benchmark for leadership in cricket.", ["ms", "dhoni", "captaincy", "ipl", "2010", "2011", "set", "benchmark", "leadership", "cricket"])
    response("The Chennai Super Kings' triumphs in the IPL in 2010 and 2011 elevated MS Dhoni to legendary status.", ["chennai", "super", "kings", "triumphs", "ipl", "2010", "2011", "elevated", "ms", "dhoni", "legendary", "status"])
    response("MS Dhoni's on-field brilliance was instrumental in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "on-field", "brilliance", "instrumental", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' success in the IPL in 2010 and 2011 was synonymous with MS Dhoni's leadership.", ["chennai", "super", "kings", "success", "ipl", "2010", "2011", "synonymous", "ms", "dhoni", "leadership"])
    response("MS Dhoni's ability to handle pressure situations was crucial in the Chennai Super Kings' IPL wins in 2010 and 2011.", ["ms", "dhoni", "ability", "handle", "pressure", "situations", "crucial", "chennai", "super", "kings", "ipl", "wins", "2010", "2011"])
    response("The Chennai Super Kings' dominance in the IPL in 2010 and 2011 was a reflection of MS Dhoni's captaincy skills.", ["chennai", "super", "kings", "dominance", "ipl", "2010", "2011", "reflection", "ms", "dhoni", "captaincy", "skills"])
    response("MS Dhoni's astute leadership was the driving force behind the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "astute", "leadership", "driving", "force", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' consistent performance in the IPL in 2010 and 2011 was attributed to MS Dhoni's guidance.", ["chennai", "super", "kings", "consistent", "performance", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "guidance"])
    response("MS Dhoni's captaincy was pivotal in the Chennai Super Kings' back-to-back IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "captaincy", "pivotal", "chennai", "super", "kings", "back-to-back", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' remarkable run in the IPL in 2010 and 2011 was fueled by MS Dhoni's inspirational leadership.", ["chennai", "super", "kings", "remarkable", "run", "ipl", "2010", "2011", "fueled", "ms", "dhoni", "inspirational", "leadership"])
    response("MS Dhoni's composed demeanor was a defining trait during the Chennai Super Kings' IPL successes in 2010 and 2011.", ["ms", "dhoni", "composed", "demeanor", "defining", "trait", "chennai", "super", "kings", "ipl", "successes", "2010", "2011"])
    response("The Chennai Super Kings' triumphs in the IPL in 2010 and 2011 showcased MS Dhoni's ability to lead from the front.", ["chennai", "super", "kings", "triumphs", "ipl", "2010", "2011", "showcased", "ms", "dhoni", "ability", "lead", "front"])
    response("MS Dhoni's leadership qualities were evident in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "leadership", "qualities", "evident", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL titles in 2010 and 2011 cemented MS Dhoni's legacy as one of the greatest captains.", ["chennai", "super", "kings", "ipl", "titles", "2010", "2011", "cemented", "ms", "dhoni", "legacy", "greatest", "captains"])
    response("MS Dhoni's strategic masterstrokes were key to the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "strategic", "masterstrokes", "key", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' IPL victories in 2010 and 2011 established MS Dhoni as a legendary figure in cricket.", ["chennai", "super", "kings", "ipl", "victories", "2010", "2011", "established", "ms", "dhoni", "legendary", "figure", "cricket"])
    response("MS Dhoni's captaincy tactics were instrumental in the Chennai Super Kings' IPL successes in 2010 and 2011.", ["ms", "dhoni", "captaincy", "tactics", "instrumental", "chennai", "super", "kings", "ipl", "successes", "2010", "2011"])
    response("The Chennai Super Kings' dominance in the IPL in 2010 and 2011 was a result of MS Dhoni's exemplary leadership.", ["chennai", "super", "kings", "dominance", "ipl", "2010", "2011", "result", "ms", "dhoni", "exemplary", "leadership"])
    response("MS Dhoni's captaincy style was admired during the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "captaincy", "style", "admired", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' remarkable performance in the IPL in 2010 and 2011 was a testament to MS Dhoni's captaincy.", ["chennai", "super", "kings", "remarkable", "performance", "ipl", "2010", "2011", "testament", "ms", "dhoni", "captaincy"])
    response("MS Dhoni's calm and composed demeanor was vital in the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "calm", "composed", "demeanor", "vital", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' consistent success in the IPL in 2010 and 2011 was attributed to MS Dhoni's leadership.", ["chennai", "super", "kings", "consistent", "success", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "leadership"])
    response("MS Dhoni's ability to remain calm under pressure was crucial for the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "ability", "remain", "calm", "pressure", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' back-to-back IPL titles in 2010 and 2011 solidified MS Dhoni's reputation as a top captain.", ["chennai", "super", "kings", "back-to-back", "ipl", "titles", "2010", "2011", "solidified", "ms", "dhoni", "reputation", "top", "captain"])
    response("MS Dhoni's leadership qualities shone through during the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "leadership", "qualities", "shone", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' IPL dominance in 2010 and 2011 was a result of MS Dhoni's exceptional captaincy skills.", ["chennai", "super", "kings", "ipl", "dominance", "2010", "2011", "result", "ms", "dhoni", "exceptional", "captaincy", "skills"])
    response("MS Dhoni's tactical brilliance was evident in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "tactical", "brilliance", "evident", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL wins in 2010 and 2011 cemented MS Dhoni's legacy as a cricketing icon.", ["chennai", "super", "kings", "ipl", "wins", "2010", "2011", "cemented", "ms", "dhoni", "legacy", "cricketing", "icon"])
    response("MS Dhoni's composed leadership style was a driving force behind the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "composed", "leadership", "style", "driving", "force", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' success in the IPL in 2010 and 2011 was a testament to MS Dhoni's cricketing acumen.", ["chennai", "super", "kings", "success", "ipl", "2010", "2011", "testament", "ms", "dhoni", "cricketing", "acumen"])
    response("MS Dhoni's ability to inspire his team was evident during the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "ability", "inspire", "team", "evident", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL triumphs in 2010 and 2011 were a testament to MS Dhoni's leadership prowess.", ["chennai", "super", "kings", "ipl", "triumphs", "2010", "2011", "testament", "ms", "dhoni", "leadership", "prowess"])
    response("MS Dhoni's calm and collected approach was crucial in the Chennai Super Kings' IPL wins in 2010 and 2011.", ["ms", "dhoni", "calm", "collected", "approach", "crucial", "chennai", "super", "kings", "ipl", "wins", "2010", "2011"])
    response("The Chennai Super Kings' back-to-back IPL victories in 2010 and 2011 solidified MS Dhoni's status as a cricketing legend.", ["chennai", "super", "kings", "back-to-back", "ipl", "victories", "2010", "2011", "solidified", "ms", "dhoni", "status", "cricketing", "legend"])
    response("MS Dhoni's leadership during the IPL in 2010 and 2011 was lauded by cricketing pundits worldwide.", ["ms", "dhoni", "leadership", "ipl", "2010", "2011", "lauded", "cricketing", "pundits", "worldwide"])
    response("The Chennai Super Kings' exceptional performance in the IPL in 2010 and 2011 was attributed to MS Dhoni's guidance.", ["chennai", "super", "kings", "exceptional", "performance", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "guidance"])
    response("MS Dhoni's ability to keep his cool under pressure was vital for the Chennai Super Kings' IPL successes in 2010 and 2011.", ["ms", "dhoni", "ability", "keep", "cool", "pressure", "vital", "chennai", "super", "kings", "ipl", "successes", "2010", "2011"])
    response("The Chennai Super Kings' IPL dominance in 2010 and 2011 was a testament to MS Dhoni's exceptional leadership qualities.", ["chennai", "super", "kings", "ipl", "dominance", "2010", "2011", "testament", "ms", "dhoni", "exceptional", "leadership", "qualities"])
    response("MS Dhoni's captaincy was crucial in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "captaincy", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL titles in 2010 and 2011 elevated MS Dhoni to legendary status in the cricketing world.", ["chennai", "super", "kings", "ipl", "titles", "2010", "2011", "elevated", "ms", "dhoni", "legendary", "status", "cricketing", "world"])
    response("MS Dhoni's calm demeanor was a calming influence on the Chennai Super Kings' IPL campaign in 2010 and 2011.", ["ms", "dhoni", "calm", "demeanor", "calming", "influence", "chennai", "super", "kings", "ipl", "campaign", "2010", "2011"])
    response("The Chennai Super Kings' dominance in the IPL in 2010 and 2011 was attributed to MS Dhoni's exceptional captaincy.", ["chennai", "super", "kings", "dominance", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "exceptional", "captaincy"])
    response("MS Dhoni's leadership was instrumental in the Chennai Super Kings' back-to-back IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "leadership", "instrumental", "chennai", "super", "kings", "back-to-back", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' IPL victories in 2010 and 2011 showcased MS Dhoni's exceptional cricketing acumen.", ["chennai", "super", "kings", "ipl", "victories", "2010", "2011", "showcased", "ms", "dhoni", "exceptional", "cricketing", "acumen"])
    response("MS Dhoni's captaincy tactics were crucial for the Chennai Super Kings' IPL success in 2010 and 2011.", ["ms", "dhoni", "captaincy", "tactics", "crucial", "chennai", "super", "kings", "ipl", "success", "2010", "2011"])
    response("The Chennai Super Kings' remarkable IPL performances in 2010 and 2011 were a testament to MS Dhoni's leadership.", ["chennai", "super", "kings", "remarkable", "ipl", "performances", "2010", "2011", "testament", "ms", "dhoni", "leadership"])
    response("MS Dhoni's ability to handle pressure situations was crucial for the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "ability", "handle", "pressure", "situations", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL triumphs in 2010 and 2011 solidified MS Dhoni's reputation as one of the greatest captains in cricket history.", ["chennai", "super", "kings", "ipl", "triumphs", "2010", "2011", "solidified", "ms", "dhoni", "reputation", "greatest", "captains", "cricket", "history"])
    response("MS Dhoni's strategic decisions were pivotal in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "strategic", "decisions", "pivotal", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' success in the IPL in 2010 and 2011 was a testament to MS Dhoni's exceptional leadership.", ["chennai", "super", "kings", "success", "ipl", "2010", "2011", "testament", "ms", "dhoni", "exceptional", "leadership"])
    response("MS Dhoni's composed demeanor was a calming presence in the Chennai Super Kings' IPL campaigns in 2010 and 2011.", ["ms", "dhoni", "composed", "demeanor", "calming", "presence", "chennai", "super", "kings", "ipl", "campaigns", "2010", "2011"])
    response("The Chennai Super Kings' dominant performances in the IPL in 2010 and 2011 were a reflection of MS Dhoni's leadership.", ["chennai", "super", "kings", "dominant", "performances", "ipl", "2010", "2011", "reflection", "ms", "dhoni", "leadership"])
    response("MS Dhoni's captaincy prowess was on display during the Chennai Super Kings' IPL triumphs in 2010 and 2011.", ["ms", "dhoni", "captaincy", "prowess", "display", "chennai", "super", "kings", "ipl", "triumphs", "2010", "2011"])
    response("The Chennai Super Kings' IPL titles in 2010 and 2011 were a result of MS Dhoni's exceptional leadership qualities.", ["chennai", "super", "kings", "ipl", "titles", "2010", "2011", "result", "ms", "dhoni", "exceptional", "leadership", "qualities"])
    response("MS Dhoni's tactical acumen was crucial for the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "tactical", "acumen", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' success in the IPL in 2010 and 2011 was a testament to MS Dhoni's tactical brilliance.", ["chennai", "super", "kings", "success", "ipl", "2010", "2011", "testament", "ms", "dhoni", "tactical", "brilliance"])
    response("MS Dhoni's leadership during the IPL in 2010 and 2011 was praised by cricketing experts worldwide.", ["ms", "dhoni", "leadership", "ipl", "2010", "2011", "praised", "cricketing", "experts", "worldwide"])
    response("The Chennai Super Kings' IPL dominance in 2010 and 2011 was a testament to MS Dhoni's cricketing intelligence.", ["chennai", "super", "kings", "ipl", "dominance", "2010", "2011", "testament", "ms", "dhoni", "cricketing", "intelligence"])
    response("MS Dhoni's astute captaincy was instrumental in the Chennai Super Kings' IPL successes in 2010 and 2011.", ["ms", "dhoni", "astute", "captaincy", "instrumental", "chennai", "super", "kings", "ipl", "successes", "2010", "2011"])
    response("The Chennai Super Kings' IPL triumphs in 2010 and 2011 showcased MS Dhoni's exceptional leadership abilities.", ["chennai", "super", "kings", "ipl", "triumphs", "2010", "2011", "showcased", "ms", "dhoni", "exceptional", "leadership", "abilities"])
    response("MS Dhoni's calm demeanor under pressure was a key factor in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "calm", "demeanor", "pressure", "key", "factor", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' back-to-back IPL titles in 2010 and 2011 established MS Dhoni as a cricketing icon.", ["chennai", "super", "kings", "back-to-back", "ipl", "titles", "2010", "2011", "established", "ms", "dhoni", "cricketing", "icon"])
    response("MS Dhoni's leadership qualities were pivotal in the Chennai Super Kings' IPL dominance in 2010 and 2011.", ["ms", "dhoni", "leadership", "qualities", "pivotal", "chennai", "super", "kings", "ipl", "dominance", "2010", "2011"])
    response("The Chennai Super Kings' exceptional performance in the IPL in 2010 and 2011 was attributed to MS Dhoni's astute captaincy.", ["chennai", "super", "kings", "exceptional", "performance", "ipl", "2010", "2011", "attributed", "ms", "dhoni", "astute", "captaincy"])
    response("MS Dhoni's tactical brilliance was crucial for the Chennai Super Kings' IPL dominance in 2010 and 2011.", ["ms", "dhoni", "tactical", "brilliance", "crucial", "chennai", "super", "kings", "ipl", "dominance", "2010", "2011"])
    response("The Chennai Super Kings' IPL triumphs in 2010 and 2011 solidified MS Dhoni's status as one of cricket's greatest leaders.", ["chennai", "super", "kings", "ipl", "triumphs", "2010", "2011", "solidified", "ms", "dhoni", "status", "cricket's", "greatest", "leaders"])
    response("MS Dhoni's ability to lead from the front was evident during the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "ability", "lead", "front", "evident", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' consistent success in the IPL in 2010 and 2011 was a result of MS Dhoni's exceptional leadership.", ["chennai", "super", "kings", "consistent", "success", "ipl", "2010", "2011", "result", "ms", "dhoni", "exceptional", "leadership"])
    response("MS Dhoni's tactical genius was crucial in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "tactical", "genius", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL dominance in 2010 and 2011 was a testament to MS Dhoni's leadership skills.", ["chennai", "super", "kings", "ipl", "dominance", "2010", "2011", "testament", "ms", "dhoni", "leadership", "skills"])
    response("MS Dhoni's calm and composed demeanor was a key asset for the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "calm", "composed", "demeanor", "key", "asset", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' remarkable IPL successes in 2010 and 2011 were a testament to MS Dhoni's leadership abilities.", ["chennai", "super", "kings", "remarkable", "ipl", "successes", "2010", "2011", "testament", "ms", "dhoni", "leadership", "abilities"])
    response("MS Dhoni's leadership during the IPL in 2010 and 2011 was a driving force behind the Chennai Super Kings' victories.", ["ms", "dhoni", "leadership", "ipl", "2010", "2011", "driving", "force", "chennai", "super", "kings", "victories"])
    response("The Chennai Super Kings' IPL triumphs in 2010 and 2011 were a reflection of MS Dhoni's exceptional cricketing intelligence.", ["chennai", "super", "kings", "ipl", "triumphs", "2010", "2011", "reflection", "ms", "dhoni", "exceptional", "cricketing", "intelligence"])
    response("MS Dhoni's strategic captaincy was instrumental in the Chennai Super Kings' IPL dominance in 2010 and 2011.", ["ms", "dhoni", "strategic", "captaincy", "instrumental", "chennai", "super", "kings", "ipl", "dominance", "2010", "2011"])
    response("The Chennai Super Kings' IPL titles in 2010 and 2011 were a result of MS Dhoni's exceptional leadership.", ["chennai", "super", "kings", "ipl", "titles", "2010", "2011", "result", "ms", "dhoni", "exceptional", "leadership"])
    response("MS Dhoni's tactical acumen was pivotal for the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "tactical", "acumen", "pivotal", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    response("The Chennai Super Kings' IPL dominance in 2010 and 2011 was a testament to MS Dhoni's exceptional cricketing mind.", ["chennai", "super", "kings", "ipl", "dominance", "2010", "2011", "testament", "ms", "dhoni", "exceptional", "cricketing", "mind"])
    response("MS Dhoni's composed demeanor was crucial in the Chennai Super Kings' IPL victories in 2010 and 2011.", ["ms", "dhoni", "composed", "demeanor", "crucial", "chennai", "super", "kings", "ipl", "victories", "2010", "2011"])
    best_match=max(highest_prob_list,key=highest_prob_list.get)
    #print(highest_prob_list)
    if(highest_prob_list[best_match]==0):
        return "Sorry i am not trained on this topic by the developers,please ask any other question"
    return best_match
def get_response(question):
    split_message=re.split(r'\s+|[,;?!.-]\s*',question.lower())
    response=check_all_messages(split_message)
    return response
print(get_response(que))